### ISSUE TITLE
用word2vec构建词典

### ISSUE THREAD

**Issue by stay-leave** [hiDaDeng/cntext#19]
![image](https://github.com/hiDaDeng/cntext/assets/58450966/7228a94f-b52d-4cdb-83c0-09d55caa535e)
大佬你好！请问这个每个情感类的种子词的第一行是每个类的名称还是说就是那个类的种子词？

**Comment by hiDaDeng** [comment]
txt内的词，都是种子词。

**Comment by stay-leave** [comment]
谢谢大佬
